---
name: lint-verilog
on:
  pull_request:
    branches:
        - main

jobs:
  lint-verilog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: reviewdog/action-setup@v1
    - uses: 3mdeb/verilog-cleaner@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
